# Generated by Django 6.1 on 2026-08-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo_subtitulo', models.CharField(max_length=150)),
                ('texto', models.TextField()),
                ('foto_url', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='urgente',
            field=models.BooleanField(default=False),
        ),
    ]
